name: surv
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - parallel
  - jupyter
  - autopep8
  - scipy=1.5.2
  - statsmodels
  - seaborn=0.11.2
  - matplotlib=3.3.2
  - python=3.7
  - pandas=1.1.3
  - numpy=1.19.2
  - scikit-learn
  - lifelines=0.25.4
  - xlrd
  - openpyxl
  - nb_conda_kernels
  - jupyterlab
  - mamba[version='>=0.22.1']
  - snakemake=7.18.2
  - ca-certificates
  - certifi
  - openssl
