name: clinical-additivity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3
  - numpy>=1.20
  - scipy>=1.7
  - matplotlib>=3.4
  - seaborn>=0.11
  - lifelines>=0.26
  - scikit-learn>=0.24
  - statsmodels>=0.13
  - xlrd>=2.0
  - openpyxl>=3.0
  - jsonschema>=4.0
  - webcolors>=1.12
  - nbformat>=5.1
  - pip
